### PR TITLE
feat: change ready-to-transfer output to CSV

### PR DESCRIPTION
**Pull request by bajtos**
Make it easier to import the output to our spreadsheet (see the [Runbook](https://www.notion.so/spacemeridian/Runbook-How-to-Trigger-Spark-Payouts-81157006ac754fe1a07609b3392d09fb)).

### CODE REVIEW

**Review by juliangruber — APPROVED** [review]
👏

**Comment by bajtos** [comment]
@juliangruber what's the process for publishing a new version of this repository to npmjs?

**Comment by juliangruber** [comment]
npx np :)

**Comment by bajtos** [comment]
> npx np

https://github.com/Meridian-IE/cli/pull/4

**Pull request merged**
